# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Simply check whether files parse as valid python
      - id: check-ast
      # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-builtin-literals
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Checks for a common error of placing code before the docstring
      - id: check-docstring-first
      # Ensures that (non-binary) executables have a shebang
      - id: check-executables-have-shebangs
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Checks that scripts with shebangs are executable
      - id: check-shebang-scripts-are-executable
      # Checks for symlinks which do not point to anything
      - id: check-symlinks
      # This hook checks yaml files for parseable syntax
      - id: check-yaml
      # Check for debugger imports and py37+ breakpoint() calls in python source
      - id: debug-statements
        # Detects the presence of private keys
      - id: detect-private-key
      # Ensures that a file is either empty, or ends with one newline
      - id: end-of-file-fixer
      # removes UTF-8 byte order marker
      - id: fix-byte-order-marker
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
      # Assert that files in tests/ end in _test.py
      - id: name-tests-test
      # Protect specific branches from direct checkins
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "master"]
      # This hook trims trailing whitespace
      - id: trailing-whitespace

  # Check for missing licensing and copyright information.
  # The REUSE helper tool assists with achieving and confirming REUSE compliance.
  # See: https://reuse.software/
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse

ci:
  autofix_commit_msg: |
    * - auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_commit_msg: 'ci - pre-commit autoupdate'
